version: "3.7"

services:

  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/leonid/nginx_study/src:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/leonid/cert.crt:/etc/nginx/ssl/cert.crt:ro
      - /home/leonid/cert.key:/etc/nginx/ssl/cert.key:ro
    restart: always
    depends_on:
      - php
    networks:
      - app-network

  php:
    image: php:apache
    volumes:
      - /home/leonid/src:/var/www/html:ro
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    ports:
    - "9000:9000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge