version: "3.7"

services:

  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - php
    networks:
      - app-network

  php:
    image: php:8.0-fpm
    volumes:
      - ./src:/var/www/html:ro
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge